name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/ryotaroseto/ci-app:latest \
          --tag ghcr.io/ryotaroseto/ci-app:$(echo $GITHUB_SHA | head -c7) \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/ryotaroseto/ci-app:latest
          docker push ghcr.io/ryotaroseto/ci-app:$(echo $GITHUB_SHA | head -c7)
