name: Create Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: get tag name
        id: get-tag-name
        run: echo "tag-name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-name.outputs.tag-name }}
          release_name: Release ${{ steps.get-tag-name.outputs.tag-name }}
          body_path: changelog.md
